additionalRepositories:
  - url: https://github.com/emscripten-core/emsdk
tasks:
  - name: Setup
    init: |
      pyenv global system
      conda env create -f environment.yml
      conda activate pyodide-env

      pip install git+https://github.com/pyodide/pyodide-build.git
      pyodide xbuildenv install --download --url http://pyodide-cache.s3-website-us-east-1.amazonaws.com/xbuildenv/dev/xbuildenv.tar.bz2

      EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
      ../emsdk/emsdk install ${EMSCRIPTEN_VERSION}
      ../emsdk/emsdk activate ${EMSCRIPTEN_VERSION}
    command: |
      source ../emsdk/emsdk_env.sh
