name: pyodide-env
channels:
  - conda-forge
dependencies:
  - python=3.12.1
  - nodejs=20
  - ccache
  - f2c
  - swig
  - make
  - cmake
  - texinfo
  - autoconf
  - automake
  - libtool
  - wget
  - setuptools
  - gfortran
  - pip:
      - requests
      - packaging
  - anaconda-client